### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by Praveenkumar-cpu** [Praveenkumar-cpu/BusinessServiceTeam#1]
explain the task given in GitLearning.txt file

**Comment by Mokinder** [comment]
I will take this issue @Praveenkumar-cpu

**Comment by AbhishekKr-CSI** [comment]
I am trying

**Comment by kushaljambhulkar** [comment]
I will try to solve @Praveenkumar-cpu

**Comment by varshap-17** [comment]
I will try to resolve this @Praveenkumar-cpu
